import 'package:flutter/material.dart';

const defaultCategoryIcon = 'mix';

const Map<String, IconData> categoryIcons = {
  'animals': Icons.pets,
  'transports': Icons.local_taxi,
  'colors': Icons.color_lens,
  'planets': Icons.rocket,
  'countries': Icons.place_sharp,
  'geography': Icons.place_outlined,
  'abc': Icons.text_fields,
  'ac_unit': Icons.ac_unit,
  'alarm': Icons.access_alarm,
  'account': Icons.account_balance,
  'agriculture': Icons.agriculture,
  'airplanemode_active': Icons.airplanemode_active,
  'apartment': Icons.apartment,
  'bar_chart': Icons.bar_chart,
  'bathtub': Icons.bathtub,
  'sunny': Icons.sunny,
  'home': Icons.home,
  'boy': Icons.boy,
  'girl': Icons.girl,
  'family_restroom': Icons.family_restroom,
  'computer': Icons.computer,
  'tv': Icons.tv,
  'train': Icons.train,
  'subway': Icons.subway,
  'construction': Icons.construction,
  'credit_card': Icons.credit_card,
  'currency_bitcoin': Icons.currency_bitcoin,
  'bedtime': Icons.bedtime,
  'diamond': Icons.diamond,
  'calculate': Icons.calculate,
  'camera': Icons.camera,
  'camera_alt': Icons.camera_alt,
  'translate': Icons.translate,
  'photo_size_select_actual_sharp': Icons.photo_size_select_actual_sharp,
  defaultCategoryIcon: Icons.category,
};
